const API_SUCCESSFUL_HEALTH_MESSAGE = 'TUF Server is running in DEV MODE - Chrome';
const INTERACTION_MODE={
  'SIGNUP': 'SIGNUP',
};

const INTERACTION_TYPE= {
  'SYSTEM' : 'SYSTEM',
}

const INTERACTION_VALUE = {
  'ACCOUNT_CREATION' : 'ACCOUNT_CREATION',
};
const PROMOTIONAL_ONBORDING_EMAIL_SUBJECT = 'Welcome to Take You Forward - Your Journey Begins Here!';
module.exports = {
  API_SUCCESSFUL_HEALTH_MESSAGE,
  INTERACTION_MODE,
  INTERACTION_TYPE,
  INTERACTION_VALUE,
  PROMOTIONAL_ONBORDING_EMAIL_SUBJECT
};