const API_SUCCESSFUL_HEALTH_MESSAGE = 'TUF Server is running in DEV MODE - Chrome';

const PROMOTIONAL_ONBOARDING_EMAIL_SUBJECT =
  'Welcome to Take You Forward - Your Journey Starts Here!';

const INTERACTION_MODE = {
  SIGNUP: 'SIGNUP',
};

const INTERACTION_TYPE = {
  SYSTEM: 'SYSTEM',
};

const INTERACTION_VALUE = {
  ACCOUNT_CREATION: 'ACCOUNT_CREATION',
};

const LOYALTY_TIER = Object.freeze({
  GOLD: 'Gold',
  SILVER: 'Silver',
  BRONZE: 'Bronze',
});

const LOYALTY_TIER_THRESHOLD = Object.freeze({
  SILVER: 5001,
  GOLD: 15001,
});

module.exports = {
  API_SUCCESSFUL_HEALTH_MESSAGE,
  PROMOTIONAL_ONBOARDING_EMAIL_SUBJECT,
  INTERACTION_MODE,
  INTERACTION_TYPE,
  INTERACTION_VALUE,
  LOYALTY_TIER,
  LOYALTY_TIER_THRESHOLD,
};